---
title: "Introduction au NLP"
author: "raniafhm"
date: "2025-17-03"
format: html
---


## Qu'est-ce que le traitement du langage naturel ? 

### **Qu’est ce qu'un langage naturel ?**

Il existe plusieurs définitions pour définir le concept de langage naturel (https://dictionnary.com/) . 

1. Un ensemble de mots et les systèmes de leur utilisation communs à un peuple appartenant à la même communauté ou nation, à la même zone géographique ou à la même tradition culturelle.


2. La communication par la voix de manière spécifiquement humaine, en utilisant des sons arbitraires de façon conventionnelle avec des significations conventionnelles.


3. Le système de signes ou de symboles linguistiques considéré dans l'abstrait (opposé à la parole).


4. Tout ensemble ou système de tels symboles utilisés de manière plus ou moins uniforme par un certain nombre de personnes, leur permettant ainsi de communiquer intelligiblement entre elles.


5. Tout système de symboles formalisés, signes, sons, gestes, ou autres, utilisé ou conçu comme un moyen de communiquer la pensée, l’émotion, etc. : le langage des mathématiques ; la langue des signes. Les moyens de communication utilisés par les animaux.

Ainsi, on peut voir le traitement du langage naturel comme un ensemble de recherche et de développement visant à modéliser et à reproduire, à l’aide de machines, la capacité humaine à produire et à comprendre des énoncés linguistiques à des fins de communication.
Le langage est ainsi un concept complexe et ambigu. Son interprétation s’accompagne de nombreuses connaissances implicites (expressions, métaphores, métonymies...)  et de bon sens, ce qui est très compliqué à retranscrire à un ordinateur. 


Exemples : 
J’ai lu un article sur le droit des femmes dans le journal. 
J’ai lu un article sur le droit des femmes dans le métro. 
