project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Cours introduction NLP"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 1_intro.qmd
        text: Introduction au NLP
      - href: 2_tokenization.qmd
        text: Qu'est ce que la tokenization ?
      - href: 3_preprocessing.qmd
        text: Prétraitement des données 
      - href: 4_embedding.qmd
        text: Word Embedding
      - href: 5_ressources.qmd
        text: Ressources  
        
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
