project:
  type: website
  
execute:
  freeze: auto

website:
  title: "Cours introduction au Webscraping"

  page-footer:
    right: "Ce site a été créé avec [Quarto](https://quarto.org/)"
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    contents:
      - href: 1_intro.qmd
        text: Introduction au NLP
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true
